name: "Build a ROCK"
description: "Pack an OCI image with Rockcraft"
inputs:
  path:
    description: 'The location of the Rockcraft project. Defaults to the base of the repository'
    default: '.'
  args:
    description: 'The arguments and options to pass to the `rockcraft` command'
    default: 'pack --verbosity trace'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        set -x
        sudo systemctl enable snapd
    - name: Install rockcraft from "edge"
      run: sudo snap install rockcraft --classic --edge
      shell: bash
    - name: Setup LXD
      uses: canonical/setup-lxd@v0.1.0
      with:
        channel: 5.9/stable
    - name: Ensure LXD is initialized
      run: |
        lxd init --auto
        lxd waitready
      shell: bash
    - name: Run `rockcraft pack`
      working-directory: ${{ inputs.path }}
      run: rockcraft ${{ inputs.args }}
      shell: bash
