name: Test the action

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-action:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup LXD
      uses: canonical/setup-lxd@90d76101915da56a42a562ba766b1a77019242fd
      with:
        channel: 5.10/stable
    - uses: ./
      with:
        path: tests